version: 2.1
jobs:
  test:
    docker:
      - image: 'circleci/openjdk:8u171-jdk-browsers'

    steps:
      - add_ssh_keys
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - checkout
      - node/install:
          node-version: "latest"

      - run: git clone git@github.com:globalworming/botc-unofficial-frontend.git
      - run:
          name: frontend
          background: true
          command: |
            cd botc-unofficial-frontend
            npm install
            npm start

      - run: git clone git@github.com:globalworming/botc-unofficial-backend.git
      - run:
          name: start backend
          background: true
          command: |
            cd botc-unofficial-backend
            mvn spring-boot:run


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: poll applications
          command: |
            sh .circleci/waitForSutReady.sh

      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          background: true
          command: |
            mkdir selenium-log
            java -jar selenium-server-standalone-3.5.3.jar -log selenium-log/selenium.log

      - verify_end_to_end:
          stage: "LOCAL_FRONTEND_WITH_MOCKED_INTEGRATIONS"
      - verify_end_to_end:
          stage: "LOCAL_FRONTEND_INTEGRATED"
      - verify_end_to_end:
          stage: "LOCAL_REST_API"



commands:
  verify_end_to_end:
    description: "run mvn verify and store results"
    parameters:
      stage:
        type: string
        default: "LOCAL_REST_API"
    steps:
      - run:
          command: |
            mvn clean verify -P << parameters.stage >> -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url=http://localhost:4444/wd/hub
          when: always
      - run:
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - run:
          command: |
            mkdir -p ~/test-results/summary-report/
            cp target/site/<< parameters.stage >>/serenity-summary.html ~/test-results/summary-report/<< parameters.stage >>.html
          when: always

      - store_test_results:
          path: ~/test-results/
      - store_artifacts:
          path: ~/test-results/

workflows:
  build_and_test:
    jobs:
      - test
orbs:
  node: circleci/node@2.1.0