version: 2.1
jobs:
  startFrontend:
    docker:
      - image: 'circleci/node:latest'

    steps:
      - add_ssh_keys
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git clone git@github.com:globalworming/botc-unofficial-frontend.git
      - run:
          name: frontend
          background: true
          command: |
            cd botc-unofficial-frontend
            npm install
            npm start &

  startBackend:
    docker:
      - image: 'circleci/openjdk:8u171-jdk'

    steps:
      - add_ssh_keys
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git clone git@github.com:globalworming/botc-unofficial-backend.git

      - run:
          name: start backend
          background: true
          command: |
            cd botc-unofficial-backend
            mvn spring-boot:run

  startSelenium:
    docker:
      - image: 'circleci/openjdk:8u171-jdk'
    steps:
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          background: true
          command: |
            mkdir selenium-log
            java -jar selenium-server-standalone-3.5.3.jar -log selenium-log/selenium.log

  waitForSutReady:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: poll applications
          background: true
          command: |
            sh .circleci/waitForSutReady.sh
  test:
    docker:
      - image: 'circleci/openjdk:8u171-jdk-browsers'

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - doendtoend:
          stage: "LOCAL_FRONTEND_WITH_MOCKED_INTEGRATIONS"
      - doendtoend:
          stage: "LOCAL_FRONTEND_INTEGRATED"
      - doendtoend:
          stage: "LOCAL_REST_API"

      - run: mkdir -p ~/test-results/summary-report/

      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/test-results/summary-report

commands:
  doendtoend:
    description: "run mvn verify and store results"
    parameters:
      stage:
        type: string
        default: "LOCAL_REST_API"
    steps:
      - run:
          command: |
            mvn clean verify -P << parameters.stage >> -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url=http://localhost:4444/wd/hub
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            cp target/site/<< parameters.stage >>/serenity-summary.html ~/test-results/summary-report/<< parameters.stage >>.html
          when: always


workflows:
  version: 2
  build_and_test:
    jobs:
#      - startFrontend
#      - startBackend
#      - startSelenium
#      - waitForSutReady
      - test:
#          requires:
#            - waitForSutReady
          filters:
            branches:
              only: master