jobs:
  startFrontend:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - run: git clone git@github.com:globalworming/botc-unofficial-frontend.git
      - run:
          name: start frontend
          background: true
          command: |
            cd botc-unofficial-frontend
            yarn i; yarn start

  startBackend:
    docker:
      - image: circleci/openjdk:8u171-jdk-browsers
    working_directory: ~/repo

    steps:
      - run: git clone git@github.com:globalworming/botc-unofficial-backend.git

      - run:
          name: setup backend
          background: true
          command: |
            cd botc-unofficial-backend
            mvn spring-boot:run

  startSelenium:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          background: true
          command: |
            mkdir selenium-log
            java -jar selenium-server-standalone-3.5.3.jar -log selenium-log/selenium.log
  test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean verify

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

      - run:
          name: Save test results
          command: |
            rm -rf ./target/site/serenity/fontawesome-free-5.7.2-web
            cp -r ./target/site/serenity ~/test-results/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/serenity
orbs:
  node: circleci/node@2.1
version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - startFrontend
      - startBackend
      - startSelenium
      - test:
          requires:
            - startFrontend
            - startBackend
            - startSelenium
          filters:
            branches:
              only: master